### ISSUE TITLE
problems to run https_server.go

### ISSUE THREAD

**Issue by ArnoldoR** [jcbsmpsn/https-example#1]
when "go run https_server.go", I get "open client.crt: no such file or directory"...
How I could generate this file?

**Comment by jcbsmpsn** [comment]
Try:

```sh
openssl req \
    -x509 \
    -nodes \
    -newkey rsa:2048 \
    -keyout client.key \
    -out client.crt \
    -days 3650 \
    -subj "/C=GB/ST=London/L=London/O=Global Security/OU=IT Department/CN=*"
```

It's down in the troubleshooting section. I searched for `client.crt` to find it.

I realize the setup section of the doc is pretty weak. I was really just using this as a way to preserve the different kinds of TLS/certificate related problems and configuration options I had to troubleshoot.

**Comment by ArnoldoR** [comment]
Thanks very much…

 the code is running …

Thanks…
